name: Spring Boot & Gradle CI/CD

on:
  push: # 깃허브 main 브랜치에 push가 됐을 때 실행
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
# 환경 변수 설정
env:
  S3_BUCKET_NAME: deploystudy-github-action
  ZIP_FILE_NAME: deploy-package.zip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 저장소 코드 가져오기
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 실행 권한 부여 & 빌드 실행
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # test 제외 빌드
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      # 배포용 디렉토리 생성
      - name: Create deploy directory
        run: mkdir -p deploy

      # 빌드된 JAR 파일 복사
      - name: Copy Jar file to deploy directory
        run: cp ./build/libs/*.jar ./deploy

      # ZIP 파일 생성
      - name: Compress deploy files
        run: zip -r ./$ZIP_FILE_NAME ./deploy
        shell: bash

      # AWS 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3에 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$ZIP_FILE_NAME s3://$S3_BUCKET_NAME/
